### ISSUE TITLE
Nuttx support in upstream OpenOCD

### ISSUE THREAD

**Issue by gmsotavio** [sony/openocd-nuttx#4]
Hi, I'd like to know if is planed to add NuttX support in the upstream branch of OpenOCD or if will following as a separed project.

Regards,
Otavio

**Comment by masayuki2009** [comment]
Hi,

Our patch to the OpenOCD upstream is under review at the following URL but needs more reviewers.
So could you please login to the gerrit and leave Code-Review +1 ?

   http://openocd.zylin.com/#/c/4103/

Thanks,
Masayuki

**Comment by MasayukiIshikawa** [comment]
@gmsotavio Today, we are happy to announce that our patch has been merged to the upstream.

http://openocd.zylin.com/#/c/4103/
